# Copyright 2018 Etsy Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

# see: https://github.com/apache/airflow/blob/1.10.3/airflow/contrib/operators/bigquery_operator.py

name: bigquery_operator
operator_class: BigQueryOperator
operator_class_module: airflow.contrib.operators.bigquery_operator 
schema_extends: base
parameters_jsonschema:
    properties:
        sql:
            type: string
        destination_dataset_table:
            type: string
        write_disposition:
            type: string
        create_disposition:
            type: string
        allow_large_results:
            type: boolean
        flatten_results:
            type: boolean
        bigquery_conn_id:
            type: string
        delegate_to:
            type: string
        udf_config:
            type: array
        use_legacy_sql:
            type: boolean
        maximum_billing_tier:
            type: integer
        maximum_bytes_billed:
            type: number
        api_resource_configs:
            type: object
            additionalProperties:
                type: string
        schema_update_options:
            type: object
            additionalProperties:
                type: string
        query_params:
            type: array
        labels:
            type: object
            additionalProperties:
                type: string
        priority:
            type: string
        time_partitioning:
            type: object
            additionalProperties:
                type: string
        cluster_fields:
            type: array
            items:
                type: string
        location:
            type: string

    required:
        - sql
        - destination_dataset_table
